# Generated by Django 4.1 on 2023-10-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0002_emailbox_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbox',
            name='email_username',
            field=models.CharField(max_length=256, verbose_name='Имя пользователя'),
        ),
    ]
